import Navbar from '@common/navbar/Navbar';
import MainLayout from '@components/layouts/MainLayout';
import { GetLayout } from '@shared/--types';

import Head from 'next/head';
import { FC, ReactElement } from 'react';

const Home: FC & GetLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <h1>hello world</h1>
      </main>
    </>
  );
};

Home.getLayout = function getLayout(_page: ReactElement) {
  return <MainLayout>page</MainLayout>;
};

export default Home;
